[package]
name = "virto-communities"
version = "0.1.0"
authors = ["b-avb <brayan.vargas.dev@gmail.com>"]
edition = "2021"

[dependencies]

dioxus = { version = "0.5", features = ["web", "router"] }
dioxus-std = { version = "0.5.0", features = ["i18n"] }

log = "0.4.19"
dioxus-logger = "0.4.1"
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.92"
unic-langid = "0.9.1"
web-sys = { version = "0.3.69", features = [
    "Document",
    "Element",
    "HtmlElement",
    "HtmlBodyElement",
    "Node",
    "NodeList",
    "Window",
    "console",
    "CssStyleDeclaration",
    "Location",
    "Navigator",
    "DomRect",
] }
gloo = "0.11.0"
infer = "0.15.0"
mime = "0.3.17"
futures-util = "0.3.30"
