name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install latest
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            target: wasm32-unknown-unknown
            default: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      
      - name: Install dependencies
        run: cargo install dioxus-cli@0.5.0

      - name: Build
        run: dx build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: ./dist
  